name: Run Automation Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run tests
        run: |
          chmod +x ./gradlew
          ./gradlew clean testApi
          ./gradlew testWeb

      - name: List all files in build directory (debug)
        if: always()
        run: |
          echo ":: List of all files in build ::"
          find build -type f | sort

      - name: Upload all reports for debugging
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: all-reports-debug
          path: build/reports/**/*.*

      - name: Upload API Cucumber HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-cucumber-html
          path: build/reports/tests/testApi/api-cucumber.html

      - name: Upload API Cucumber JSON Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-cucumber-json
          path: build/reports/tests/testApi/api-cucumber.json

      - name: Upload Web Cucumber HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: web-cucumber-html
          path: build/reports/tests/testWeb/web-cucumber.html

      - name: Upload Web Cucumber JSON Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: web-cucumber-json
          path: build/reports/tests/testWeb/web-cucumber.json
