name: Run tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 23
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 23

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Run testApi and testWeb
        run: ./gradlew clean testApi testWeb

      - name: List all report files
        run: |
          echo "Listing reports..."
          find build/reports/tests -type f

      - name: Upload API test reports
        uses: actions/upload-artifact@v4
        with:
          name: api-test-report
          path: |
            build/reports/tests/testApi/api-cucumber.html
            build/reports/tests/testApi/api-cucumber.json

      - name: Upload Web UI test reports
        uses: actions/upload-artifact@v4
        with:
          name: web-test-report
          path: |
            build/reports/tests/testWeb/web-cucumber.html
            build/reports/tests/testWeb/web-cucumber.json
