# ==== REPORT WEB UI ====
- name: Upload Web Cucumber HTML Report
  if: always()
  continue-on-error: true
  uses: actions/upload-artifact@v4
  with:
    name: web-cucumber-html
    path: build/reports/web-cucumber.html

- name: Upload Web Cucumber JSON Report
  if: always()
  continue-on-error: true
  uses: actions/upload-artifact@v4
  with:
    name: web-cucumber-json
    path: build/reports/web-cucumber.json

# ==== REPORT API ====
- name: Upload API Cucumber HTML Report
  if: always()
  continue-on-error: true
  uses: actions/upload-artifact@v4
  with:
    name: api-cucumber-html
    path: build/reports/api-cucumber.html

- name: Upload API Cucumber JSON Report
  if: always()
  continue-on-error: true
  uses: actions/upload-artifact@v4
  with:
    name: api-cucumber-json
    path: build/reports/api-cucumber.json
