name: Run Automation Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      # Jalankan test API dan Web UI secara terpisah
      - name: Run API Tests
        run: ./gradlew clean testApi

      - name: Run Web UI Tests
        run: ./gradlew testWeb

      # ==== REPORT API ====
      - name: Upload API Cucumber HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-cucumber-html
          path: build/reports/tests/api-cucumber.html

      - name: Upload API Cucumber JSON Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-cucumber-json
          path: build/reports/tests/api-cucumber.json

      # ==== REPORT WEB UI ====
      - name: Upload Web Cucumber HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: web-cucumber-html
          path: build/reports/tests/web-cucumber.html

      - name: Upload Web Cucumber JSON Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: web-cucumber-json
          path: build/repor
