name: Run Automation Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Run API Tests Only
        run: ./gradlew apiTest

      - name: Upload Cucumber HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-report
          path: build/reports/tests/api-cucumber.html

      - name: Upload Cucumber JSON Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-json-report
          path: build/reports/tests/api-cucumber.json
