name: Run Automation Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      # ===== Run Tests =====
      - name: Run API Tests
        run: ./gradlew clean testApi

      - name: Run Web UI Tests
        run: ./gradlew testWeb

      # ===== List report files (debugging) =====
      - name: List report files
        if: always()
        run: |
          echo ":: Web UI reports ::"
          ls -al build/reports/tests/web-cucumber.* || echo "Web report not found"
          echo ":: API reports ::"
          ls -al build/reports/tests/api-cucumber.* || echo "API report not found"

      # ===== Upload API Reports =====
      - name: Upload API Cucumber HTML Report
        if: always()
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: api-cucumber-html
          path: build/reports/tests/api-cucumber.html

      - name: Upload API Cucumber JSON Report
        if: always()
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: api-cucumber-json
          path: build/reports/tests/api-cucumber.json

      # ===== Upload Web UI Reports =====
      - name: Upload Web Cucumber HTML Report
        if: always()
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: web-cucumber-html
          path: build/reports/tests/web-cucumber.html

      - name: Upload Web Cucumber JSON Report
        if: always()
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: web-cucumber-json
          path: build/reports/tests/web-cucumber.json
